// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5tO1LBdxGznHQRmghVQdZF8YY-ijjpX8',
    appId: '1:787565255536:android:fc0d9c8dfd4334e4104db5',
    messagingSenderId: '787565255536',
    projectId: 'scorpio-9bfe9',
    databaseURL: 'https://scorpio-9bfe9-default-rtdb.firebaseio.com',
    storageBucket: 'scorpio-9bfe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfUJg7lqS8uqaNbixGj5KCwy2Q6xvOA0I',
    appId: '1:787565255536:ios:63ca311f85320021104db5',
    messagingSenderId: '787565255536',
    projectId: 'scorpio-9bfe9',
    databaseURL: 'https://scorpio-9bfe9-default-rtdb.firebaseio.com',
    storageBucket: 'scorpio-9bfe9.appspot.com',
    iosClientId: '787565255536-48ndpc87csb51025dbn5mj9jes47fd7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.scorpioRides',
  );
}
